language: node_js
node_js:
  - 12
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - npm run test:coveralls
  - npm run test:cypress:ci